# -*- coding: utf-8 -*-
"""hw3_tests

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wwkH7v3canLxqyE1EzUHVketPcNKie2C
"""

from unittest import TestCase
from hw3 import FlashCards

class TestFlashCards(TestCase):
    def setUp(self):
        self.card = FlashCards(path=path)

    def test_play(self):
        answer = self.card.play()
        self.assertEqual(answer, 'Done! 0 of 3 words correct.')

    def test_add_word(self, russian, english):
        answer = self.card.add_word(russian, english)
        self.assertEqual(answer, "Succesfully added word '{}'.".format(russian))

    def test_delete_word(self, russian):
        answer = self.card.delete_word(russian)
        self.assertEqual(answer, "Succesfully deleted word '{}'.".format(russian))

test = TestFlashCards()
test.setUp()

test.test_play()

test.test_delete_word('бежать')

test.test_add_word('летать','fly')