# -*- coding: utf-8 -*-
"""hw3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14TZ1vGjImKW7DOZiHdCE6bafTTEjikEL
"""

import json
import random

pip install mock

path = 'json_dictionary.json'

class FlashCards:

    def __init__(self, path): 
        '''
        Прочитает пары слов из указанного файла в формате json. 
        Создаст все требующиеся атрибуты.  
        '''

        with open(path, 'r',encoding='utf-8') as f:
          self.__dict_fr_play = json.load(f)
        self._words = list(self.__dict_fr_play.keys())
  
    def play(self) -> str:
        '''
        Выдает русские слова из словаря в рандомном порядке, 
        сверяет введенный пользователем перевод с правильным 
        (регистр введенного слова при этом не важен), 
        пока слова в словаре не закончатся. 
        Возвращает строку с количеством правильных ответов/общим количеством 
        слов в словаре (см пример работы). 
        '''
        if not self.words:
          return "Dicionary is empty!"
        __right_answer_cnt = 0 #счетчик правильных ответов
        random.shuffle(self.words) #Случайным образом перемешиваем словарь
        for i in self.words:
          print(i)
          __answer = input()
          __right_answer_cnt += 1 if self.__dict_fr_play[i].lower() == __answer.lower() else 0
        return ("Done! {} of {} words correct.".format(__right_answer_cnt, len(self.words)))
            
    def add_word(self, russian: str, english: str) -> str:
        '''
        Добавляет в словарь новую пару слов, 
        если русского слова еще нет в словаре.
        Возвращает строку в зависимоти от результата.
        '''
        if russian not in self.__dict_fr_play:
          self.__dict_fr_play.update(dict({russian: english}))
          return ("Succesfully added word '{}'.".format(russian))
        else:
          return ("'{}' already in dictionary. ".format(russian))

    def delete_word(self, russian: str) -> str:
        '''
        Удаляет из словаря введенное русское слово
        и соответсвующее ему английское. 
        Возвращает строку в зависимоти от результата. 
        '''
        if russian in self.__dict_fr_play:
          self.__dict_fr_play.pop(russian)
          return ("Succesfully deleted word '{}'.".format(russian))
        else:
          return ("'{}' not in dictionary. ".format(russian))
    
    @property
    def words(self):
        return self._words